### ISSUE TITLE
Wrong error message in new bot creation page

### ISSUE THREAD

**Issue by OrBin** [argmaxml/annotbot#1]
When using the "New Bot" tab, pressing one of the button that should lead to the next stages ("Classes", "Data to Label", "Bot Ready") gives an unrelated error message.

If the value in "Bot name" field is shorter than 2 characters, the error is "Bot name too long".
If the value in "Bot name" field is longer than 2 characters, the error is "Bot name too short".

I've tried to reproduce it, running the project on my machine, but failed since I obviously don't have access to the DB :laughing:

**Comment by urigoren** [comment]
Thanks for noticing,
I've fixed the error messages.

In the code of `server.py`,  there's a variable called `debug_mode`, if you set it to `True` then `sqlite` should be set as your database provider, and you should be able to run the code.

However, in order to test the bot itself, you'll need to create a bot and get a `token` from https://t.me/botfather
